title: Chenyu Zhao's Homepage
page-top-title: Chenyu Zhao
top-section-bg-text: Towards future
home-subtitle: Chenyu Zhao&ensp;|&ensp;赵辰宇
copyright-text: '&copy; Chenyu Zhao 2026. All Rights Reserved.'
